// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Aceptar Solicitud', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Aceptar Solicitud', async function() {
    // Test name: Aceptar Solicitud
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:5173/ |  | 
    await driver.get("http://localhost:5173/")
    // 2 | setWindowSize | 1280x680 |  | 
    await driver.manage().window().setRect({ width: 1280, height: 680 })
    // 3 | type | id=email | unicef | 
    await driver.findElement(By.id("email")).sendKeys("unicef")
    // 4 | mouseOver | css=.MuiButtonBase-root |  | 
    {
      const element = await driver.findElement(By.css(".MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 5 | type | id=password | asdf1234 | 
    await driver.findElement(By.id("password")).sendKeys("asdf1234")
    // 6 | click | css=.MuiButtonBase-root |  | 
    await driver.findElement(By.css(".MuiButtonBase-root")).click()
    // 7 | click | css=.MuiPaper-root:nth-child(1) .MuiListItem-root:nth-child(7) .MuiTypography-root |  | 
    await driver.findElement(By.css(".MuiPaper-root:nth-child(1) .MuiListItem-root:nth-child(7) .MuiTypography-root")).click()
    // 8 | click | css=.MuiTableRow-root:nth-child(6) a > .MuiSvgIcon-root |  | 
    await driver.findElement(By.css(".MuiTableRow-root:nth-child(6) a > .MuiSvgIcon-root")).click()
    // 9 | mouseOver | css=.css-13tvvzp-MuiButtonBase-root-MuiButton-root |  | 
    {
      const element = await driver.findElement(By.css(".css-13tvvzp-MuiButtonBase-root-MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 10 | click | css=.css-13tvvzp-MuiButtonBase-root-MuiButton-root |  | 
    await driver.findElement(By.css(".css-13tvvzp-MuiButtonBase-root-MuiButton-root")).click()
    // 11 | mouseOver | css=.css-1meuvs7-MuiButtonBase-root-MuiButton-root |  | 
    {
      const element = await driver.findElement(By.css(".css-1meuvs7-MuiButtonBase-root-MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 12 | click | css=.css-1meuvs7-MuiButtonBase-root-MuiButton-root |  | 
    await driver.findElement(By.css(".css-1meuvs7-MuiButtonBase-root-MuiButton-root")).click()
    // 13 | mouseOut | css=.css-1meuvs7-MuiButtonBase-root-MuiButton-root |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 14 | click | css=.css-ugxt08-MuiButtonBase-root-MuiButton-root |  | 
    await driver.findElement(By.css(".css-ugxt08-MuiButtonBase-root-MuiButton-root")).click()
    // 15 | click | css=.MuiPaper-root:nth-child(1) .MuiListItem-root:nth-child(11) > .MuiButtonBase-root |  | 
    await driver.findElement(By.css(".MuiPaper-root:nth-child(1) .MuiListItem-root:nth-child(11) > .MuiButtonBase-root")).click()
  })
})
