// Generated by Selenium IDE
import { Builder, By, Key, until} from 'selenium-webdriver'
import assert from 'assert'

describe('CREATE VOLUNTEER', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })

  const waitClick = async (driver, by) => {
    return await driver.wait(until.elementLocated(by),120000).click();
  }

  const waitAndSend = async (driver, by, keys) => {
    return await driver.wait(until.elementLocated(by),120000).sendKeys(keys);
  }

  const waitClickHoldAndPerform = async (driver, by) => {
    const element = await driver.findElement(by)
    await driver.actions({ bridge: true }).move({ duration: 1000, origin: element }).press().move({ x: 0, y: 50 }).release().perform()
  }
  it('CREATE VOLUNTEER', async function() {
    await driver.get("http://localhost:5173/")
    await driver.manage().window().setRect({ width: 1936, height: 1066 })
    await driver.findElement(By.id("email")).sendKeys("testong")
    await driver.findElement(By.id("password")).sendKeys("testong")
    await waitClick(driver, By.xpath("//button[@type=\'button\']"))
    await waitClick(driver, By.xpath("//div[@id=\'root\']/div/nav/div/div/div[2]/ul/li[5]/div/div/span"))
    await waitClick(driver, By.xpath("/html/body/div[1]/div/main/div[2]/div/div[1]/div/div/div[2]/a/div/button"))

    await waitAndSend(driver, By.id(":r7:"),"testvolunteertest@test.com")
    await waitAndSend(driver, By.id(":r9:"),"testvolunteertest")
    await waitAndSend(driver, By.id(":rb:"),"testvolunteertest")
    await waitAndSend(driver, By.id(":rd:"),"testvolunteertest")
    await waitAndSend(driver, By.id(":rl:"),"05-04-2001")
    await waitAndSend(driver, By.id(":rr:"),"05-04-2023")
    await waitAndSend(driver, By.id(":rt:"),"05-04-2023")
    await waitAndSend(driver, By.id(":rp:"),"0")
    await waitAndSend(driver, By.id(":rv:"),"testdireccion")
    await waitAndSend(driver, By.id(":r11:"),"99999")
    await waitAndSend(driver, By.id(":r13:"),"test")
    await waitAndSend(driver, By.id(":r15:"),"test")
    await waitAndSend(driver, By.id(":r17:"),"test")
    await waitAndSend(driver, By.id(":r19:"),"test")
    await waitAndSend(driver, By.id(":r1b:"),"test")
    await waitAndSend(driver, By.id(":r1f:"),"999999999")
    await waitAndSend(driver, By.id(":rh:"), "99999997T")

    await waitClickHoldAndPerform(driver, By.id(":rj:"))
    await waitClick(driver,By.xpath("//li[contains(.,\'Hombre\')]"))
   
    await waitClickHoldAndPerform(driver, By.id(":r1d:"))
    await waitClick(driver,By.xpath("//li[contains(.,\'Sí\')]"))

    await waitClickHoldAndPerform(driver, By.id(":rn:"))
    await waitClick(driver,By.xpath("//li[contains(.,\'Soltero\')]"))

    await waitClickHoldAndPerform(driver, By.id(":rf:"))
    await waitClick(driver,By.xpath("//li[contains(.,\'DNI\')]"))

    await waitClick(driver, By.xpath("/html/body/div[1]/div/main/div[2]/div/div/div[22]/div/button"))

    await waitClick(driver, By.xpath("/html/body/div[3]/div[3]/div/div/div/div[3]/div/button"))

    await waitClick(driver, By.xpath("/html/body/div[1]/div/main/div[2]/div/div[2]/div[2]/table/tbody/tr[2]/td[7]/div/div/button"))
    await waitClick(driver, By.xpath("/html/body/div[3]/div[3]/div/div/div/div/button"))

    await driver.close()
  })
})
