// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Creación Actividad', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Creación Actividad', async function() {
    // Test name: Creación Actividad
    // Step # | name | target | value | comment
    // 1 | open | http://localhost:5173/ |  | 
    await driver.get("http://localhost:5173/")
    // 2 | setWindowSize | 1280x680 |  | 
    await driver.manage().window().setRect({ width: 1280, height: 680 })
    // 3 | type | id=email | testong | 
    await driver.findElement(By.id("email")).sendKeys("testong")
    // 4 | type | id=password | testong | 
    await driver.findElement(By.id("password")).sendKeys("testong")
    // 5 | sendKeys | id=password | ${KEY_ENTER} | 
    await driver.findElement(By.id("password")).sendKeys(Key.ENTER)
    // 6 | mouseOver | css=.MuiButtonBase-root |  | 
    {
      const element = await driver.findElement(By.css(".MuiButtonBase-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 7 | click | css=.MuiButtonBase-root |  | 
    await driver.findElement(By.css(".MuiButtonBase-root")).click()
    // 8 | click | css=.MuiPaper-root:nth-child(1) .MuiListItem-root:nth-child(7) .MuiTypography-root |  | 
    await driver.findElement(By.css(".MuiPaper-root:nth-child(1) .MuiListItem-root:nth-child(7) .MuiTypography-root")).click()
    // 9 | mouseOver | css=.css-ugxt08-MuiButtonBase-root-MuiButton-root |  | 
    {
      const element = await driver.findElement(By.css(".css-ugxt08-MuiButtonBase-root-MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 10 | click | css=.css-ugxt08-MuiButtonBase-root-MuiButton-root |  | 
    await driver.findElement(By.css(".css-ugxt08-MuiButtonBase-root-MuiButton-root")).click()
    // 11 | mouseOut | css=.css-bud0xz .MuiButtonBase-root |  | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 12 | click | id=:r7: |  | 
    await driver.findElement(By.id(":r7:")).click()
    // 13 | type | id=:r7: | Recogida de fondos | 
    await driver.findElement(By.id(":r7:")).sendKeys("Recogida de fondos")
    // 14 | type | id=:r9: | Sevilla | 
    await driver.findElement(By.id(":r9:")).sendKeys("Sevilla")
    // 15 | mouseDown | id=:rb: |  | 
    {
      const element = await driver.findElement(By.id(":rb:"))
      await driver.actions({ bridge: true }).moveToElement(element).clickAndHold().perform()
    }
    // 16 | mouseUp | css=.MuiBackdrop-invisible |  | 
    {
      const element = await driver.findElement(By.css(".MuiBackdrop-invisible"))
      await driver.actions({ bridge: true }).moveToElement(element).release().perform()
    }
    // 17 | click | css=body |  | 
    await driver.findElement(By.css("body")).click()
    // 18 | click | css=.MuiMenuItem-root:nth-child(1) |  | 
    await driver.findElement(By.css(".MuiMenuItem-root:nth-child(1)")).click()
    // 19 | click | id=:rd: |  | 
    await driver.findElement(By.id(":rd:")).click()
    // 20 | type | id=:rd: | 2023-05-10T16:04 | 
    await driver.findElement(By.id(":rd:")).sendKeys("2023-05-10T16:04")
    // 21 | click | id=:rd: |  | 
    await driver.findElement(By.id(":rd:")).click()
    // 22 | click | css=.css-1bf7xiu |  | 
    await driver.findElement(By.css(".css-1bf7xiu")).click()
    // 23 | click | id=:rf: |  | 
    await driver.findElement(By.id(":rf:")).click()
    // 24 | type | id=:rf: | Mario Rey | 
    await driver.findElement(By.id(":rf:")).sendKeys("Mario Rey")
    // 25 | type | id=:rh: | - | 
    await driver.findElement(By.id(":rh:")).sendKeys("-")
    // 26 | type | id=:rj: | 5 | 
    await driver.findElement(By.id(":rj:")).sendKeys("5")
    // 27 | click | css=.css-1ezu5cl .MuiButtonBase-root |  | 
    await driver.findElement(By.css(".css-1ezu5cl .MuiButtonBase-root")).click()
    // 28 | click | css=.MuiPaper-root:nth-child(1) .MuiListItem-root:nth-child(11) .MuiTypography-root |  | 
    await driver.findElement(By.css(".MuiPaper-root:nth-child(1) .MuiListItem-root:nth-child(11) .MuiTypography-root")).click()
  })
})
