// Generated by Selenium IDE
import { Builder, By, Key, until } from 'selenium-webdriver'
import assert from 'assert'

describe('SIGN IN ONG', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })

  const waitClick = async (driver, by) => {
    return driver.wait(until.elementLocated(by), 120000).click();
  }
  
  it('SIGN IN ONG', async function() {
    // Test name: SIGN IN ONG
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:5173/")
    // 2 | setWindowSize | 516x794 | 
    await driver.manage().window().setRect({ width: 516, height: 794 })
    // 3 | type | id=email | testong
    await driver.findElement(By.id("email")).sendKeys("testong")
    // 4 | type | id=password | testong
    await driver.findElement(By.id("password")).sendKeys("testong")
    // 5 | click | xpath=//div[3] | 

    await waitClick(driver, By.xpath("//div[3]"))
    await waitClick(driver, By.xpath("//div[3]"))
    const le2 = await driver.wait(until.elementLocated(By.xpath("/html/body/div[1]/div/header/div/div/div")),120000).getText()
    assert.equal(le2, "Bienvenido, testong")

    await driver.close()
    // 9 | close |  | 
  })
})
