version: '3.1'
services:
  nginx:
    image: nginx
    restart: always
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1 
    volumes:
      - ./nginx/react.conf:/etc/nginx/conf.d/default.conf
      - ./dist/:/usr/share/nginx/html
    ports:
      - 80:80